sudo: false
language: node_js
node_js:
- '5'
notifications:
  slack: empeeric:Hsm2xE5SNniMiUAEgM0Ngcnb
deploy:
  provider: npm
  email: me@refack.com
  api_key:
    secure: Gq86gEGmI0EG2sub1BKBYyhqfDYpqWUb3/4ms39lcO9H9P109F6WHdjGNeNV/GjNhODk93lE6eYqYTcfpAaomDt4TEY7Q4tns1HOl5FsjgA8fhZMV/K/Q8VgNWBm2W7b2u5KuQWo1/IZYofGcaazEbsoSDn06ifOrjtky9i8zUk=
  on:
    tags: true
    repo: node4good/lodash-contrib
