language: node_js
node_js:
- '0.12'
- '0.10'
notifications:
  slack: empeeric:Hsm2xE5SNniMiUAEgM0Ngcnb
deploy:
  provider: npm
  email: me@refack.com
  api_key:
    secure: LW/jmPVX5PQHuMopKeeUjBysSYNrCd+8Xe+RTKyuuISpv+7tBvgJNpq2a6pSVcXC1gJDlAvTWed37JgsCKMi5vonScC45zwsWoH2HhMX/fVofn5M7AiIuozFkCbvzXm9R9aVL8lkbZEFEHhrw/ktmCg3XGNoua5+puunGrcQ4cw=
  on:
    tags: true
    node: '0.12'
    repo: TheNodeILs/lodash-contrib
